services:

  spring:
    image: ${DOCKER_USER}/homepage:latest
    container_name: gdg-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend-bridge

  mysql:
    image: mysql:8.0
    container_name: gdg-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-bridge

volumes:
  mysql_data:

networks:
  backend-bridge:
    driver: bridge
